version: "3"
services:
  graphql-container:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
